Neos:
  Neos:
    fusion:
      autoInclude:
        Flowpack.Neos.WhatsNewEditor.InMyProject: true
    nodeTypes:
      groups:
        whatsNewDashboard:
          position: 80
          label: "What's new dashboard elements"
          collapsed: false
  Flow:
    mvc:
      routes:
        Flowpack.Neos.WhatsNewEditor.InMyProject: true
